# meta-planer layer configuration

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-planer"
BBFILE_PATTERN_meta-planer = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-planer = "20"

LAYERDEPENDS_meta-planer = "core"
LAYERSERIES_COMPAT_meta-planer = "scarthgap"
