MACHINEOVERRIDES =. "imx93-11x11-lpddr4x-frdm:"
require conf/machine/imx93-11x11-lpddr4x-frdm.conf

KERNEL_DEVICETREE:append = " freescale/imx93-gunbot.dtb"

# Keep imx-boot Linux-only; M33 will be started later by U-Boot bootcmd.
IMXBOOT_TARGETS:imx93-frdm = "flash_singleboot_m33"
